version: '2'
services:

  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config02:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02a:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Router
  router01:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - shard01a
      - shard01b
      - shard02a
      - shard02b
  router02:
    image: mongo
    command: mongos --port 27018 --configdb configserver/config01:27017,config02:27017 --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - shard01a
      - shard01b
      - shard02a
      - shard02b